[program:recipe_book]
command=/data/data/com.termux/files/usr/bin/node index.js
directory=/data/data/com.termux/files/home/serve/recipe_book
autostart=true
autorestart=true
startsecs=5
startretries=5
redirect_stderr=true
stdout_logfile=/data/data/com.termux/files/home/.supervisor/logs/recipe_book.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
environment=NODE_ENV="production"
